apiVersion: v1
kind: Service
metadata:
  name: {{ include "employees.fullname" . }}-python
  labels:
    app: {{ include "employees.name" . }}-python
spec:
  type: {{ .Values.pythonService.type }}
  ports:
    - port: {{ .Values.pythonService.port }}
      targetPort: {{ .Values.pythonImage.port }}
      protocol: TCP
  selector:
    app: {{ include "employees.name" . }}-python
