apiVersion: v1
kind: Service
metadata:
  name: {{ include "employees.fullname" . }}-java
  labels:
    app: {{ include "employees.name" . }}-java
spec:
  type: {{ .Values.javaService.type }}
  ports:
    - nodePort: {{ .Values.javaService.port }}
      port: 80
      targetPort: {{ .Values.javaImage.port }}
      protocol: TCP
  selector:
    app: {{ include "employees.name" . }}-java
