apiVersion: v2
name: employees
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: 1.16.0

dependencies:
# https://www.youtube.com/watch?v=LAVCJorZ2AA
  
  - name: kube-prometheus-stack
    version: "13.13.1"
    condition: prometheus.enabled
    # enabled: true
    repository: https://prometheus-community.github.io/helm-charts
  
