name: Cron CI

on:
  push:
    paths:
    - 'my-cron-actions/**'
    - '.github/workflows/cron-ci.yml'

env:
  OWNER: UMA_SURYA_SAI
  APP_VERSION: v5

defaults:
  run:
    working-directory: my-cron-actions

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: Build and tag the Docker Image
    runs-on: ubuntu-latest
    steps:
    - name: Chekout
      uses: actions/checkout@v2
    - name: Set up QEMU
      #This allows us to build images targeted at more than one platform and also build Arm images.
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Login to GitHub Docker packages
      uses: docker/login-action@v1 
      with:
        registry: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ secrets.MYGITHUB_TOKEN }}
    - uses: docker/build-push-action@v2
      id: docker_build
      name: Build & push Docker image to DokerHub
      with:
        push: true
        context: my-cron-actions
        tags: |
          surya407/cron-test:${{ env.APP_VERSION }}
          surya407/cron-test:latest
          umasuryasai/ci-cd-testing/cron-java-test:${{ env.APP_VERSION }}
          umasuryasai/ci-cd-testing/cron-java-test:latest
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}

    # #################
    # ADDITIONAL CODE #
    # #################
    # - uses: docker/build-push-action@v1
    #   name: Build & push Docker image to DokerHub
    #   with:
    #     repository: surya407/cron-test
    #     tags: ${{ env.APP_VERSION }}
    #     registry: docker.io
    #     path: my-cron-actions
    #     username: ${{ secrets.DOCKERHUB_USER }}
    #     password: ${{ secrets.DOCKERHUB_PASSWORD }}
    # - uses: docker/build-push-action@v1
    #   name: Build & publish Docker image to GitHub Packages
    #   with:
    #     repository: umasuryasai/ci-cd-testing/cron-test
    #     tags: ${{ env.APP_VERSION }}
    #     registry: docker.pkg.github.com
    #     path: my-cron-actions
    #     username: ${{ github.actor }}
    #     password: ${{ secrets.MYGITHUB_TOKEN }}
