name: Cron CI

on:
  push:
    paths:
    - 'my-cron-actions/**'
    - '.github/workflows/cron-ci.yml'

env:
  OWNER: UMA_SURYA
  APP_VERSION: v1

defaults:
  run:
    working-directory: my-cron-actions

jobs:
  build:
    name: Build and tag the Docker Image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        ls -al
        cat crontab
    - uses: docker/build-push-action@v2
      name: Build & push Docker image to DokerHub
      with:
        repository: surya407/cron-test
        tags: ${{ env.APP_VERSION }}
        registry: docker.io
        # dockerfile: Dockerfile
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    # - uses: docker/build-push-action@v1
    #   name: Build & publish Docker image to GitHub Packages
    #   with:
    #     repository: umasuryasai/ci-cd-testing/cron-test
    #     tags: ${{ env.APP_VERSION }}
    #     registry: docker.pkg.github.com
    #     dockerfile: Dockerfile
    #     username: ${{ github.actor }}
    #     password: ${{ secrets.MYGITHUB_TOKEN }}
