name: Docker Image CI

on:
  push:
    branches: [ master ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ master ]


jobs:

  build:
    name: Build and tag the Docker Image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file others/Dockerfile --tag surya407/test:v2
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Look up images
      run: docker image ls
    - name: Push image
      run: docker push surya407/test:v2
    # - name: Push to Docker Hub
    #   uses: docker/build-push-action@v2
    #   with:
    #     file: ./others/Dockerfile
    #     username: ${{ secrets.DOCKERHUB_USER }}
    #     password: ${{ secrets.DOCKERHUB_PASSWORD }}
    #     repository: surya407/test:v2
    #     push: true
    #     tag: surya407/test:v2