name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:

  build:
    name: Build and tag the Docker Image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file others/Dockerfile --tag surya407/httpd:$(date +%s)
    - name: Push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: surya407/test:v2
        tag_with_ref: true

  # push_to_registry:
  #   name: Push Docker image to Docker Hub
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Check out the repo
  #     uses: actions/checkout@v2
  #   - name: Push to Docker Hub
  #     uses: docker/build-push-action@v2
  #     with:
  #       username: ${{ secrets.DOCKERHUB_USER }}
  #       password: ${{ secrets.DOCKERHUB_PASSWORD }}
  #       repository: surya407/test
  #       tag_with_ref: true